
jobs: 
  build-backend: 
    docker: 
      - 
        image: "circleci/node:13.8.0"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - backend-build
      - 
        run: 
          command: |
              cd backend
              npm i
              npm run build
          name: "Back-end build"
      - 
        save_cache: 
          key: backend-build
          paths: 
            - backend/node_modules
      - 
        save_cache: 
          key: backend-dist
          paths: 
            - backend/dist
      - 
        slack/notify: 
          event: fail
          template: basic_fail_1
  
workflows: 
  default: 
    jobs: 
      - build-frontend
      - build-backend
      - 
        test-frontend: 
          requires: 
            - build-frontend
      - 
        test-backend: 
          requires: 
            - build-backend
      - 
        scan-frontend: 
          requires: 
            - build-frontend
      - 
        scan-backend: 
          requires: 
            - build-backend
      - 
        deploy-infrastructure: 
          filters: 
            branches: 
              only: 
                - main
          requires: 
            - test-frontend
            - test-backend
            - scan-frontend
            - scan-backend
      - 
        configure-infrastructure: 
          requires: 
            - deploy-infrastructure
      - 
        run-migrations: 
          requires: 
            - configure-infrastructure
      - 
        deploy-backend: 
          requires: 
            - run-migrations
      - 
        deploy-frontend: 
          requires: 
            - run-migrations
      - 
        smoke-test: 
          requires: 
            - deploy-backend
            - deploy-frontend
      - 
        cloudfront-update: 
          requires: 
            - smoke-test
      - 
        cleanup: 
          requires: 
            - cloudfront-update
